development:
  base: "http://localhost:3735"
  password_reset: "/#/reset-password"
  unsubscribe: "/#/unsubscribe"

test:
  base: "http://localhost:2727"
  password_reset: "/#/reset-password"
  unsubscribe: "/#/unsubscribe"

staging:
  base: "http://demo.zooniverse.org/panoptes-front-end"
  password_reset: "/#/reset-password"
  unsubscribe: "/#/unsubscribe"

production:
  base: "http://localhost:3735"
  password_reset: "/#/reset-password"
  unsubscribe: "/#/unsubscribe"
